pipeline{
    agent {label 'master'}		
	 stages {
			stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'gitlab', url: 'https://gitlab.Pratian.com/projects.skillassure/Waste-Management-backend.git']]])
            }
		}

		
			stage ( 'SonarReport'){
			steps {
			
					sh 'java -version'
					sh 'mvn -version'
					sh 'mvn package sonar:sonar'    					
		}
			
		}
		  }
    }
